CREATE TABLE inmdb.per_dtls_we
(
    sr_no                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    pno                    VARCHAR(255)                            NOT NULL,
    test                   VARCHAR(255),
    blood_group_code       VARCHAR(255),
    aadhar_number          VARCHAR(255),
    pan_number             VARCHAR(255),
    voter_id               VARCHAR(255),
    religion_code          VARCHAR(255),
    nationality_code       VARCHAR(255),
    marital_status_code    VARCHAR(255),
    date_of_marriage       TIMESTAMP WITHOUT TIME ZONE,
    official_mobile_number VARCHAR(255),
    personal_mobile_number VARCHAR(255),
    unit_code              VARCHAR(255),
    command_code           VARCHAR(255),
    gov_email_id           VARCHAR(255),
    nud_email_id           VARCHAR(255),
    personal_email_id      VARCHAR(255),
    date_of_joining        TIMESTAMP WITHOUT TIME ZONE,
    rank_code              VARCHAR(255),
    date_of_commission     TIMESTAMP WITHOUT TIME ZONE,
    date_of_seniority      TIMESTAMP WITHOUT TIME ZONE,
    cadre_code             VARCHAR(255),
    branch_code            VARCHAR(255),
    entry_type             VARCHAR(255),
    icard_number           VARCHAR(255),
    icard_type             VARCHAR(255),
    gx_unit                VARCHAR(255),
    medical_category       VARCHAR(255),
    medical_category_date  TIMESTAMP WITHOUT TIME ZONE,
    date_of_retirement     TIMESTAMP WITHOUT TIME ZONE,
    domicile_state         VARCHAR(255),
    designation            VARCHAR(255),
    designation_idm        VARCHAR(255),
    unit_idm               VARCHAR(255),
    unit_id                INTEGER,
    command_id             INTEGER,
    cadre_id               INTEGER,
    branch_id              INTEGER,
    rank_id                INTEGER,
    CONSTRAINT pk_per_dtls_we PRIMARY KEY (sr_no)
);

CREATE TABLE inmdb.per_mst_we
(
    sr_no                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    pno                      VARCHAR(255)                            NOT NULL,
    first_name               VARCHAR(255),
    middle_name              VARCHAR(255),
    last_name                VARCHAR(255),
    test                     VARCHAR(255),
    gender                   VARCHAR(255),
    date_of_birth            TIMESTAMP WITHOUT TIME ZONE,
    place_of_birth           VARCHAR(255),
    user_type_code           VARCHAR(255),
    is_active                INTEGER,
    full_name                VARCHAR(255),
    dashboard_allow_yn       INTEGER,
    admin_control_yn         INTEGER,
    admin_cr_report_allow_yn INTEGER,
    super_admin_control_yn   INTEGER,
    CONSTRAINT pk_per_mst_we PRIMARY KEY (sr_no)
);

ALTER TABLE inmdb.per_mst_we
    ADD CONSTRAINT uc_6e668a1a2120a89819728dff0 UNIQUE (pno);

ALTER TABLE inmdb.per_dtls_we
    ADD CONSTRAINT FK_PER_DTLS_WE_ON_PNO FOREIGN KEY (pno) REFERENCES inmdb.per_mst_we (pno);